### ISSUE TITLE
Fix letter case of W3 Schools link on resources page

### ISSUE THREAD

**Issue by imattman** [PDXPythonPirates/pythonpirates.org#86]
On resources page:  https://www.pythonpirates.org/resources/#html-css-and-javascript

Link currently reads: `W3 Schools - WORLD’S LARGEST WEB DEVELOPER SITE`

Update to a better description or at the very least use lower case:
`W3 Schools - World's largest web developer site`

**Comment by brjinks** [comment]
Hi can I claim this issue?

**Comment by imattman** [comment]
> Hi can I claim this issue?

Hey Bryan.  Thanks for taking interest!

Are you a member of our meetup and I missed it?  We are really trying to encourage our meetup group to jump and become more comfortable with Git.

That said, we welcome contributions.  If no one else picks it up in the next couple of days, it's all yours 👍

**Comment by brjinks** [comment]
Thanks. I'm not a member of the meetup, but since no one else has claimed the issue I can start working on it.

**Comment by brjinks** [comment]
I made a PR #88

**Comment by imattman** [comment]
@brjinks thanks for the contribution!

**Comment by brjinks** [comment]
@imattman You're welcome!
